# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 339)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 220, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 30, 41, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setValidator(QtGui.QIntValidator())
        self.lineEdit.setText("0")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 20, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 30, 16, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 41, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setValidator(QtGui.QIntValidator())
        self.lineEdit_2.setText("0")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 30, 41, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setValidator(QtGui.QIntValidator())
        self.lineEdit_3.setText("0")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 30, 41, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setValidator(QtGui.QIntValidator())
        self.lineEdit_4.setText("0")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 16, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 30, 41, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setValidator(QtGui.QIntValidator())
        self.lineEdit_5.setText("0")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 70, 41, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setValidator(QtGui.QIntValidator())
        self.lineEdit_6.setText("0")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 70, 41, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setValidator(QtGui.QIntValidator())
        self.lineEdit_7.setText("0")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 70, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 70, 16, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 70, 41, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setValidator(QtGui.QIntValidator())
        self.lineEdit_8.setText("0")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 70, 20, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 70, 16, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(200, 70, 41, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setValidator(QtGui.QIntValidator())
        self.lineEdit_9.setText("0")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(360, 70, 41, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setValidator(QtGui.QIntValidator())
        self.lineEdit_10.setText("0")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 70, 16, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(200, 110, 41, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.setValidator(QtGui.QIntValidator())
        self.lineEdit_11.setText("0")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 110, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(240, 110, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(90, 110, 20, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 110, 41, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.setValidator(QtGui.QIntValidator())
        self.lineEdit_12.setText("0")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 110, 41, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_13.setValidator(QtGui.QIntValidator())
        self.lineEdit_13.setText("0")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(270, 110, 41, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_14.setValidator(QtGui.QIntValidator())
        self.lineEdit_14.setText("0")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(310, 110, 16, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(360, 110, 41, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_15.setValidator(QtGui.QIntValidator())
        self.lineEdit_15.setText("0")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(170, 110, 16, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(200, 160, 41, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_16.setValidator(QtGui.QIntValidator())
        self.lineEdit_16.setText("0")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(340, 160, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(240, 160, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(90, 160, 20, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(50, 160, 41, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_17.setValidator(QtGui.QIntValidator())
        self.lineEdit_17.setText("0")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 160, 41, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_18.setValidator(QtGui.QIntValidator())
        self.lineEdit_18.setText("0")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(270, 160, 41, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_19.setValidator(QtGui.QIntValidator())
        self.lineEdit_19.setText("0")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(310, 160, 16, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(360, 160, 41, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_20.setValidator(QtGui.QIntValidator())
        self.lineEdit_20.setText("0")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(170, 160, 16, 16))
        self.label_20.setObjectName("label_20")
        self.TextEdit_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEdit_21.setGeometry(QtCore.QRect(480, 30, 91, 151))
        self.TextEdit_21.setObjectName("TextEdit_21")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(510, 0, 47, 13))
        self.label_21.setObjectName("label_21")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 40, 151, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(40, 0, 301, 21))
        self.label_22.setObjectName("label_22")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Make calculations"))
        self.label.setText(_translate("MainWindow", "x1"))
        self.label_2.setText(_translate("MainWindow", "x2"))
        self.label_3.setText(_translate("MainWindow", "x3"))
        self.label_4.setText(_translate("MainWindow", "x4"))
        self.label_5.setText(_translate("MainWindow", "="))
        self.label_6.setText(_translate("MainWindow", "="))
        self.label_7.setText(_translate("MainWindow", "x3"))
        self.label_8.setText(_translate("MainWindow", "x1"))
        self.label_9.setText(_translate("MainWindow", "x4"))
        self.label_10.setText(_translate("MainWindow", "x2"))
        self.label_11.setText(_translate("MainWindow", "="))
        self.label_12.setText(_translate("MainWindow", "x3"))
        self.label_13.setText(_translate("MainWindow", "x1"))
        self.label_14.setText(_translate("MainWindow", "x4"))
        self.label_15.setText(_translate("MainWindow", "x2"))
        self.label_16.setText(_translate("MainWindow", "="))
        self.label_17.setText(_translate("MainWindow", "x3"))
        self.label_18.setText(_translate("MainWindow", "x1"))
        self.label_19.setText(_translate("MainWindow", "x4"))
        self.label_20.setText(_translate("MainWindow", "x2"))
        self.label_21.setText(_translate("MainWindow", "Ответ"))
        self.label_22.setText(
            _translate("MainWindow", "if there are less than 4 equations, leave fields with a value of 0"))
        self.pushButton_2.setText(_translate("MainWindow", "Write response to file"))
